name: Simple CI for Smart Agriculture Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v3  # Updated to version 3 to use a newer Node version

    # Step 2: Set up Node.js environment
    - name: Set up Node.js
      uses: actions/setup-node@v3  # Updated to version 3 to use a newer Node version
      with:
        node-version: '14'

    # Step 3: Install dependencies
    - name: Install dependencies
      run: npm install

    # Step 4: Compile TypeScript
    - name: Compile TypeScript
      run: npx tsc

    # Step 5: Run Jest tests
    - name: Run tests
      run: npx jest